# -*- coding: utf-8 -*-
"""Tamizhan skills .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oo6_Kfac5YyIcXkQUexxLrhzTEcG-P1-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df=pd.read_csv("/content/Sample - Superstore.csv", encoding='latin1')

df

print("DataFrame Info:")
df.info()
print("\nMissing Values per Column:")
df.isnull().sum()

print(f"Number of duplicate rows before removal: {df.duplicated().sum()}")

missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0] # Filter out columns with no missing values if any

if not missing_values.empty:
    plt.figure(figsize=(12, 6))
    sns.barplot(x=missing_values.index, y=missing_values.values)
    plt.title('Distribution of Missing Values')
    plt.xlabel('Columns')
    plt.ylabel('Number of Missing Values')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()
else:
    print("No missing values found in the DataFrame. A plot is not necessary.")

missing_values = df.isnull().sum()

plt.figure(figsize=(15, 7))
sns.barplot(x=missing_values.index, y=missing_values.values, palette='viridis')
plt.title('Distribution of Missing Values Across Columns', fontsize=16)
plt.xlabel('Columns', fontsize=12)
plt.ylabel('Number of Missing Values', fontsize=12)
plt.xticks(rotation=90, ha='right', fontsize=10)
plt.yticks(fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

missing_values = df.isnull().sum()

plt.figure(figsize=(15, 7))
sns.barplot(x=missing_values.index, y=missing_values.values, hue=missing_values.index, palette='viridis', legend=False)
plt.title('Distribution of Missing Values Across Columns', fontsize=16)
plt.xlabel('Columns', fontsize=12)
plt.ylabel('Number of Missing Values', fontsize=12)
plt.xticks(rotation=90, ha='right', fontsize=10)
plt.yticks(fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
print("DataFrame Info after date conversion:")
df.info()

descriptive_stats = df.describe()
print(descriptive_stats)

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Histogram for Sales
sns.histplot(df['Sales'], ax=axes[0], kde=True, color='skyblue')
axes[0].set_title('Distribution of Sales')
axes[0].set_xlabel('Sales')
axes[0].set_ylabel('Frequency')

# Histogram for Profit
sns.histplot(df['Profit'], ax=axes[1], kde=True, color='lightcoral')
axes[1].set_title('Distribution of Profit')
axes[1].set_xlabel('Profit')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

category_sales_profit = df.groupby('Category')[['Sales', 'Profit']].sum().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart for Sales by Category
sns.barplot(x='Category', y='Sales', data=category_sales_profit, ax=axes[0], palette='viridis')
axes[0].set_title('Total Sales by Category', fontsize=14)
axes[0].set_xlabel('Category', fontsize=12)
axes[0].set_ylabel('Total Sales', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)

# Bar chart for Profit by Category
sns.barplot(x='Category', y='Profit', data=category_sales_profit, ax=axes[1], palette='plasma')
axes[1].set_title('Total Profit by Category', fontsize=14)
axes[1].set_xlabel('Category', fontsize=12)
axes[1].set_ylabel('Total Profit', fontsize=12)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

category_sales_profit = df.groupby('Category')[['Sales', 'Profit']].sum().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart for Sales by Category
sns.barplot(x='Category', y='Sales', data=category_sales_profit, ax=axes[0], hue='Category', palette='viridis', legend=False)
axes[0].set_title('Total Sales by Category', fontsize=14)
axes[0].set_xlabel('Category', fontsize=12)
axes[0].set_ylabel('Total Sales', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)

# Bar chart for Profit by Category
sns.barplot(x='Category', y='Profit', data=category_sales_profit, ax=axes[1], hue='Category', palette='plasma', legend=False)
axes[1].set_title('Total Profit by Category', fontsize=14)
axes[1].set_xlabel('Category', fontsize=12)
axes[1].set_ylabel('Total Profit', fontsize=12)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()


sub_category_sales_profit = df.groupby('Sub-Category')[['Sales', 'Profit']].sum().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(20, 7)) # Increased figure size for sub-categories

# Bar chart for Sales by Sub-Category
sns.barplot(x='Sub-Category', y='Sales', data=sub_category_sales_profit, ax=axes[0], hue='Sub-Category', palette='viridis', legend=False)
axes[0].set_title('Total Sales by Sub-Category', fontsize=14)
axes[0].set_xlabel('Sub-Category', fontsize=12)
axes[0].set_ylabel('Total Sales', fontsize=12)
axes[0].tick_params(axis='x', rotation=90) # Rotate labels for better readability

# Bar chart for Profit by Sub-Category
sns.barplot(x='Sub-Category', y='Profit', data=sub_category_sales_profit, ax=axes[1], hue='Sub-Category', palette='plasma', legend=False)
axes[1].set_title('Total Profit by Sub-Category', fontsize=14)
axes[1].set_xlabel('Sub-Category', fontsize=12)
axes[1].set_ylabel('Total Profit', fontsize=12)
axes[1].tick_params(axis='x', rotation=90) # Rotate labels for better readability

plt.tight_layout()
plt.show()

region_sales_profit = df.groupby('Region')[['Sales', 'Profit']].sum().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart for Sales by Region
sns.barplot(x='Region', y='Sales', data=region_sales_profit, ax=axes[0], hue='Region', palette='viridis', legend=False)
axes[0].set_title('Total Sales by Region', fontsize=14)
axes[0].set_xlabel('Region', fontsize=12)
axes[0].set_ylabel('Total Sales', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)

# Bar chart for Profit by Region
sns.barplot(x='Region', y='Profit', data=region_sales_profit, ax=axes[1], hue='Region', palette='plasma', legend=False)
axes[1].set_title('Total Profit by Region', fontsize=14)
axes[1].set_xlabel('Region', fontsize=12)
axes[1].set_ylabel('Total Profit', fontsize=12)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

segment_sales_profit = df.groupby('Segment')[['Sales', 'Profit']].sum().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart for Sales by Segment
sns.barplot(x='Segment', y='Sales', data=segment_sales_profit, ax=axes[0], hue='Segment', palette='viridis', legend=False)
axes[0].set_title('Total Sales by Segment', fontsize=14)
axes[0].set_xlabel('Segment', fontsize=12)
axes[0].set_ylabel('Total Sales', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)

# Bar chart for Profit by Segment
sns.barplot(x='Segment', y='Profit', data=segment_sales_profit, ax=axes[1], hue='Segment', palette='plasma', legend=False)
axes[1].set_title('Total Profit by Segment', fontsize=14)
axes[1].set_xlabel('Segment', fontsize=12)
axes[1].set_ylabel('Total Profit', fontsize=12)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

daily_sales = df.groupby('Order Date')['Sales'].sum().reset_index()

plt.figure(figsize=(15, 7))
sns.lineplot(x='Order Date', y='Sales', data=daily_sales)
plt.title('Daily Sales Over Time', fontsize=16)
plt.xlabel('Order Date', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

numerical_df = df[['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit']]
correlation_matrix = numerical_df.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Variables', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

df['Order_Month_Year'] = df['Order Date'].dt.to_period('M')

monthly_sales_trend = df.groupby('Order_Month_Year')['Sales'].sum().reset_index()

monthly_sales_trend['Order_Month_Year'] = monthly_sales_trend['Order_Month_Year'].dt.to_timestamp()

plt.figure(figsize=(18, 8))
sns.lineplot(x='Order_Month_Year', y='Sales', data=monthly_sales_trend)
plt.title('Monthly Sales Trend Over Time', fontsize=18)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Total Sales', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sales_by_ship_mode = df.groupby('Ship Mode')['Sales'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Ship Mode', y='Sales', data=sales_by_ship_mode, hue='Ship Mode', palette='viridis', legend=False)
plt.title('Total Sales by Ship Mode', fontsize=16)
plt.xlabel('Ship Mode', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

sales_by_segment = df.groupby('Segment')['Sales'].sum()

plt.figure(figsize=(10, 8))
plt.pie(sales_by_segment, labels=sales_by_segment.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('viridis', len(sales_by_segment)))
plt.title('Proportion of Total Sales by Customer Segment', fontsize=16)
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Sales', y='Profit', data=df, alpha=0.6)
plt.title('Sales vs. Profit Scatter Plot', fontsize=16)
plt.xlabel('Sales', fontsize=12)
plt.ylabel('Profit', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

total_sales = df['Sales'].sum()
print(f"Total Sales: {total_sales:.2f}")

total_profit = df['Profit'].sum()
print(f"Total Profit: {total_profit:.2f}")

profit_margin = (total_profit / total_sales) * 100
print(f"Overall Profit Margin: {profit_margin:.2f}%")

num_orders = df['Order ID'].nunique()
average_order_value = total_sales / num_orders
print(f"Average Order Value: {average_order_value:.2f}")

profit_per_order = total_profit / num_orders
print(f"Profit per Order: {profit_per_order:.2f}")